// tests go here; this will not be compiled when this package is used as a library
EEPROM.writeb(0, 1)
EEPROM.writew(1, 123)
EEPROM.writeb(3, 2)
EEPROM.writew(4, 456)
EEPROM.writeb(6, 3)
EEPROM.writew(7, 789)
serial.writeLine("A")
serial.writeNumber(EEPROM.readb(0))
serial.writeString(",")
serial.writeNumber(EEPROM.readw(1))
serial.writeLine("")
serial.writeNumber(EEPROM.readb(3))
serial.writeString(",")
serial.writeNumber(EEPROM.readw(4))
serial.writeLine("")
serial.writeNumber(EEPROM.readb(6))
serial.writeString(",")
serial.writeNumber(EEPROM.readw(7))
serial.writeLine("")
